### ISSUE TITLE
[JOSS Review] Add DOIs for references

### ISSUE THREAD

**Issue by bmcfee** [boisgera/bitstream#10]
[Reference https://github.com/openjournals/joss-reviews/issues/541#issuecomment-359456428]

The `References` section of `paper.md` does not currently provide DOIs for cited items.  Please either add them, or mark here each one that lacks a DOI.

**Comment by boisgera** [comment]
AFAICT, only the bitstream refernce has a DOI (via zenodo), I have added it.

Commit: 306ee2b1aba706995e1aa74f2b32f10404ee3f7f

**Comment by bmcfee** [comment]
Seems reasonable.
