### ISSUE TITLE
Python 3.7/3.8 support

### ISSUE THREAD

**Issue by gerion0** [boisgera/bitstream#17]
Is it possible to run bitstream with Python 3.7 and Python 3.8?

In the setup.py and Readme only Python 3.6 is mentioned as well as in pypi. If not, can you support it?

**Comment by boisgera** [comment]
There has been no new release for a while (almost 2 years), and Python 3.7 and 3.8 were not out yet.
So I ran the test suite manually with Python 3.7 and 3.8 (on Linux only) and everything works as expected (except for some deprecation warnings that I have not investigated yet).

The project information and test environnements should be updated and a new release issued, but in the meantime you should be ok if you install the current version of bitstream for Python 3.7 or 3.8.

Cheers,

SB

**Comment by boisgera** [comment]
Follow the technical issues on #21
