### ISSUE TITLE
Not a bug but a pair of features

### ISSUE THREAD

**Issue by ismaelharunid** [boisgera/bitstream#19]
Really great module except for one really key feature is missing and while it may not be required for many situations, it would be for many types of bitstream encoding.  To the point then...

Your wonderful module doesn't allow for random bit counts.  This is quite important when dealing with actual bits or values which have a non 1, 8, 16, 32, 64 increment.  So I have forked it and am looking over the feasibility of adding 2 additional methods.  Something like readbits and writebits, which will take one additional argument to their existing equivalents.  So readbits would be `BitStream.read(self, type, n_bits, n=1)` and `BitStream.write(self, data, type, n_bits)`.  Such that even the type is whatever number of bits native-ly, n_bits would determine how many actual bits were pulled from the stream or written to the stream per item (n).   

So after I have figured out if the existing code is supportive for such new features I will add some feasibility code to my fork and report back my conclusions.  Seems like it would be a good addition.  But maybe you have different ideas?   But either way I think this is helpful.  Cheers.

**Comment by boisgera** [comment]
Hi Ismael,

I designed the `BitStream` class to have a *very* small interface (constructor, `write`, `read`, that's it !), to be very simple and easy to learn. I am not sure that I understand your use case in detail (AFAICT you want to enforce a given number of bits read or written but I may be wrong ; I don't see how you want to reconcile this with the "natural" bit length associated to the type parameter). But obviously there are some contexts where a larger set of methods is more confortable. You may even be able to achieve your goal without needing to rewrite anything, by extending the `BitStream` class (in pure Python).

Cheers,
SB

**Comment by ismaelharunid** [comment]
Yes, after digging through the code I sort of got that idea.  i had supposed it was something closer to my use case and yes I certainly could use it as is.  But I think I have chosen to roll my own for the requirements I have and since strangely there doesn't seem to be anything out there for actually streaming bits as buffer or IO in a generic way.  Seems sort of impossible, so maybe I just don't know about and have not seen it.  Anyway, I will keep in touch as your work is very inspirational.  My approach is fairly different but possibly it will be of help to you also.  I haven't made a repo yet, but I already have most of the base functionality done.  I will probably make a repo and upload it with the next 48 hours.

Cheers
