### ISSUE TITLE
[JOSS Review] Install from source documentation

### ISSUE THREAD

**Issue by bmcfee** [boisgera/bitstream#4]
Hello!  I'm reviewing your [JOSS submission](https://github.com/openjournals/joss-reviews/issues/541), and will be creating a handful of issues to keep tabs on points in the review form.

The instructions to install from source are listed in the `contributing` section, but I think most people would expect to see this (also) in the `installation` section.

**Comment by boisgera** [comment]
Hello Brian! Thanks for taking the time to do this!
I'll have a look at your issues asap.

For the installation section, you're right, that's certainly where I would look for such instructions.
The rationale here was to avoid exposing the user to Cython if it was not needed (I can't help the developer here ...). But I may as well transfer the section with the appropriate warnings. 

OK, that's on my TODO list.

**Comment by boisgera** [comment]
Commit: 2c59c399c6a4d093c6b6cc80e9cc37c8dc4f7312

**Comment by bmcfee** [comment]
LGTM.
