### ISSUE TITLE
[JOSS Review] List dependencies in install scripts

### ISSUE THREAD

**Issue by bmcfee** [boisgera/bitstream#6]
[Reference thread https://github.com/openjournals/joss-reviews/issues/541#issuecomment-359456428]

The setup script does not currently list the requirements for installation, runtime, or testing, so users have to install these explicitly.  It would be better to have `requires` and `extras_require` sections of the setup to automate this process, and handle optional dependencies for testing and doc building.

**Comment by boisgera** [comment]
Yes, I do not rely on the setup script for dependencies ... but I wish I could :)

AFAICT:

 1. using `extras_require` to deal with pyyaml (needed for the tests) and mkdocs (to build the docs) should be straightforward (say with an extra called `dev`).

 2. numpy used to be a giant pain to include as a dependency in setup.py. Nowadays, it is much easier (wheels, yay !) ... but **as long as you don't need its C headers, which we do**. Last time I looked, there were unofficial hacks floating around on forums doing things in setup.py that I couldn't understand. If you know better, please tell me, I would need help on this one.

 3. Cython is similar to numpy in this respect: you need cython early in the setup.py (in imports), when the setup.py declared dependencies have not kicked in yet. So again, there are hacks (try/catch the import, replace with a dummy module, wait the setup.py to be reexecuted later when Cython is finally available) but nothing official and I can't tell how robust these methods are. Same here: if you can contribute on this point you're welcome :)

Given that I didn't know how to automate the whole process, I didn't bother doing "the right thing" with the easy part (point 1.: pyyaml and mkdocs). Do you feel that it's worth it nonetheless given the big picture? I'll have a look if you think so.

**Comment by bmcfee** [comment]
Yeah, I've been through a lot of the same hassles, and eventually gave up on cython because of it.

Maybe a decent compromise would be to have a `requirements.txt` file instead of using setup.py?  That way, new users don't need to look up the individual dependencies, and just say `pip install -r requirements.txt` before running setup.  It's not a perfect solution, but it's better than nothing.

**Comment by boisgera** [comment]
- I have added a "fat" `requirements-dev.txt` file that mainly targets the developers, and updated the documentation accordingly. 

  - The mere user still needs to do this manually: we can't install a C compiler or pip via pip anyway, so at this point it's only a matter of installing numpy. And the user should know about numpy to use the library anyway ... 

  - The user that wants to install from sources can either install "too many things" (all developer tools) easily or only Cython (manually).

**Comment by bmcfee** [comment]
This seems like a reasonable compromise to me.  Thanks for that!
