### ISSUE TITLE
[JOSS Review] BitStream constructor documentation

### ISSUE THREAD

**Issue by bmcfee** [boisgera/bitstream#9]
[Reference https://github.com/openjournals/joss-reviews/issues/541#issuecomment-359456428]

The `BitStream` constructor documentation refers the reader to the `write` method to learn what `*args, **kwargs` parameters are accepted.  Since the `write` signature is small, it would be easier to read if the constructor was described explicitly.

**Comment by boisgera** [comment]
Agreed, not convenient. I have also split the constructor documentation in two: 87f25ea63edf583aa3a4e5be4685bff3717dd12c
